### ISSUE TITLE
Device/APP/TestCase set up screen blocked

### ISSUE THREAD

**Issue by mazerpeng** [caketech/PatrolPP#1]
After launching Patrol, I cannot see the setting page of device/app/test case even the Patrol window has been enlarged to the max. I can find no way to adjust the window in order to let the setting page displayed. 

PC: 
1. OS: Win7 64 bit
2. .Net framework: 4.6.1
3. Java 8 update 161

Screenshot as below. It is what I can see the most of setting page. 
![image](https://user-images.githubusercontent.com/37332804/37339208-dbd1bede-26f4-11e8-89b5-b3541a35d0c3.png)

**Comment by caketech** [comment]
Currently,  we use 1920*1080 as system default resolution. Thanks for your reply, we will test other resolution today to fix this issue.

**Comment by mazerpeng** [comment]
The resolution of my computer is 1280*1024.

**Comment by caketech** [comment]
The resolution issue has been fixed in Ver 1.0.20, please try again, thanks.

**Comment by mazerpeng** [comment]
Works on 1.0.21.

**Comment by caketech** [comment]
Thanks for reply.
